[package]
name = "olc_codejam_2024"
version = "0.1.0"
edition = "2021"

[profile.wasm-release]
inherits = "release"
opt-level = "z"

[dependencies]
bevy = "0.15"
bevy_prototype_lyon = "0.13"

[dev-dependencies]
bevy_dylib = "0.15"

